script:
  - ./setup.sh
  - php ./example/CLI/boot.php
  - php ./example/CLI/boot.php color
  - php ./example/CLI/boot.php parse arg1 arg2 /arg3/arg4 -opt1 -opt2 opt_arg --cfg1 skip --cfg2=cfg_arg
language: php
php:
  - 7.1
  - 7.2
